authentication/urls.py
from django.urls import path
from authentication.views import login

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_series, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_series, delete_series, add_series_ajax, create_series_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-series', create_series, name='create_series'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-series/<int:id>', edit_series, name='edit_series'),
    path('delete-series/<int:id>', delete_series, name='delete_series'),
    path('create-series-ajax/', add_series_ajax, name='add_series_ajax'),
    path('create-flutter/', create_series_flutter, name='create_series_flutter'),
]

series_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class SeriesForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

authentication/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)

main/views.py
from django.shortcuts import render, redirect
from main.forms import SeriesForm
from main.models import Item
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import datetime
import json

@login_required(login_url='/login')
def show_main(request):
    series = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'series': series,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_series(request):
    form = SeriesForm(request.POST or None) 

    if form.is_valid() and request.method == "POST":
        series = form.save(commit=False)
        series.user = request.user
        series.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_series.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_series(request, id):
    # Get book berdasarkan ID
    book = Item.objects.get(pk = id)

    # Set book sebagai instance dari form
    form = SeriesForm(request.POST or None, instance=book)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_series.html", context)

def delete_series(request, id):
    series = Item.objects.get(pk = id)
    series.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def add_series_ajax(request):
    if request.method == 'POST':
        # Retrieve value name, amount, description, and user
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        # Make a new Item object with those values
        new_series = Item(name=name, amount=amount, description=description, user=user)
        new_series.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_series_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_series = Item.objects.create(
            user = request.user,
            name = data["name"],
            page = int(data["amount"]),
            description = data["description"]
        )

        new_series.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_series.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid pt-4">

  <h1 class="text-center">Add New Series</h1>
  
  <form method="POST" class="m-auto w-50">
    {% csrf_token %}
    <div class="mb-3">
      <label for="name" class="form-label">Name</label>
      <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="amount" class="form-label">Amount</label>
      <input type="number" class="form-control" id="amount" name="amount">
    </div>
    <div class="mb-3">
      <label for="description" class="form-label">Dscription</label>
      <textarea type="number" class="form-control" id="description" name="description"></textarea>
    </div>
    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>
</div>

{% endblock %}

main/templates/edit_series.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container-fluid pt-4">

    <h1 class="text-center">Add New Series</h1>
    
    <form method="POST" class="m-auto w-50">
      {% csrf_token %}
      <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input type="text" class="form-control" id="name" name="name" value={{form.instance.name}}>
      </div>
      <div class="mb-3">
        <label for="amount" class="form-label">Amount</label>
        <input type="number" class="form-control" id="amount" name="amount" value={{form.instance.amount}}>
      </div>
      <div class="mb-3">
        <label for="description" class="form-label">Dscription</label>
        <textarea type="number" class="form-control" id="description" name="description">{{form.instance.description}}</textarea>
      </div>
      <button type="submit" class="btn btn-primary w-100">Submit</button>
    </form>
  </div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
<head>
  
{% block meta %}

<div class="container">
  <div class="d-flex justify-content-center p-4">
  </div>
</div>
{% endblock meta %} 

{% block content %}
  <section class="h-100">
    <div class="container py-5 h-100">
      <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-8 col-lg-7 col-xl-6">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
            class="img-fluid" alt="Phone image">
        </div>
        <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
            {% if messages %}
        {% for message in messages %}
        <div class="toast align-items-center text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
              <div class="toast-body">
                Hello, world! This is a toast message.
              </div>
              <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
          </div>
        {% endfor %}
    {% endif %}
    
          <form method="POST" class="d-flex flex-column">
            {% csrf_token %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" id="username" name="username" class="form-control form-control-lg" />
              <label class="form-label" for="username">Username</label>
            </div>
  
            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="password" name="password" class="form-control form-control-lg" />
              <label class="form-label" for="password">Password</label>
            </div>
  
            <div class="d-flex justify-content-end align-items-center mb-4">
              <!-- Checkbox -->
              <a href="#!">Forgot password?</a>
            </div>
  
            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-lg btn-block w-100">Sign in</button>
  
            <div class="divider d-flex align-items-center my-4 w-100 text-white">
              <p class="text-center fw-bold mx-3 mb-0 block w-100">OR</p>
            </div>
            <p>
                New to Series Tracker?
            </p>
            <a class="btn btn-primary btn-lg btn-block w-100" style="background-color: #3b5998" href="{% url 'main:register' %}"
              role="button">Sign up
            </a>
          </form>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand px-3" href="#">Series Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container py-5">
  <div class="row ps-4">
    <h5>Welcome {{name}} from class {{class}}!</h5>
  </div>

  <div id="series-display" class="row p-4"></div>
  
  <div class="row">
    <div class="col pb-2 ps-4 d-flex">
      <div class="block me-5">
        <a href="{% url 'main:create_series' %}" class="btn btn-info text-white">Add New Series</a>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Add Series by AJAX
        </button>
      </div>
      <a href="{% url 'main:logout' %}" class="btn btn-danger">Logout</a>
    </div>
  </div>
  <div class="row">
    <small class="text-muted">Sesi terakhir login: {{ last_login }}</small></p>
  </div>
</div>

<div class="modal fade text-dark" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form id="form" onsubmit="return false;">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="name" class="col-form-label">Name:</label>
                      <input type="text" class="form-control" id="name" name="name"></input>
                  </div>
                  <div class="mb-3">
                      <label for="amount" class="col-form-label">Episodes:</label>
                      <input type="number" class="form-control" id="amount" name="amount"></input>
                  </div>
                  <div class="mb-3">
                      <label for="description" class="col-form-label">Description:</label>
                      <textarea class="form-control" id="description" name="description"></textarea>
                  </div>
              </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Series</button>
          </div>
      </div>
  </div>
</div>

<script>
  async function getSeries() {
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshSeries() {
        const seriesDisplay = document.getElementById("series-display")
        seriesDisplay.innerHTML = ""

        const series = await getSeries()
        
        console.log(series)
        
        series.forEach((item) => {
          const cardCol = document.createElement("div")
          cardCol.classList.add("col")

          cardCol.innerHTML = `
            <div id = "item_cards" class="card border-danger text-white bg-dark mb-3 p-3" style="width: 300px;">
              <div class="card-body">
                <h4 class="card-title">${item.fields.name}</h4>
                <span class="card-subtitle">${item.fields.description}</span>
                <p class="card-text"><small class="text">${item.fields.amount} total episodes</small></p>
                <a href="/edit-series/${item.pk}" class="btn btn-primary">Edit</a>
                <a href="/delete-series/${item.pk}" class="btn btn-danger">Delete</a>
              </div>
            </div>
            `
          
            seriesDisplay.appendChild(cardCol)
        })
      }

      refreshSeries()

      function addSeries() {
        fetch("{% url 'main:add_series_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshSeries)

        document.getElementById("form").reset()
        return false
    }

  document.getElementById("button_add").onclick = addSeries
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %} 

{% block meta %}
<title>Register</title>
{% endblock meta %} 

{% block content %}

<section class="h-100">
  <div class="container py-5 h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
      <div class="col-md-8 col-lg-7 col-xl-6">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
          class="img-fluid" alt="Phone image">
      </div>
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
          {% if messages %}
      {% for message in messages %}
      <div class="toast align-items-center text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="d-flex">
            <div class="toast-body">
              Hello, world! This is a toast message.
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
        </div>
      {% endfor %}
  {% endif %}
  
        <form method="POST" class="d-flex flex-column">
          {% csrf_token %}
          <!-- Email input -->
          <div class="form-outline mb-4">
            <input type="text" id="username" name="username" class="form-control form-control-lg" />
            <label class="form-label" for="username">Username</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-4">
            <input type="password" id="password1" name="password1" class="form-control form-control-lg" />
            <label class="form-label" for="password1">Password</label>
          </div>

          <div class="form-outline mb-4">
            <input type="password" id="password2" name="password2" class="form-control form-control-lg" />
            <label class="form-label" for="password2">Confirm Password</label>
          </div>

          <!-- Submit button -->
          <button type="submit" class="btn btn-primary btn-lg btn-block w-100" style="background-color: #3b5998">Sign up</button>

          <div class="divider d-flex align-items-center my-4 w-100 text-white">
            <p class="text-center fw-bold mx-3 mb-0 block w-100">OR</p>
          </div>
          <p>
              Already have an account?
          </p>
          <a class="btn btn-primary btn-lg btn-block w-100" href="{% url 'main:login' %}"
            role="button">Sign in
          </a>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>

  <body class="bg-dark text-white">
    {% block content %} {% endblock content %}
  </body>
</html>